### ISSUE TITLE
after 0.7.4 patch, I found some glitch 

### ISSUE THREAD

**Issue by syju1984** [Avalon304/Functioning-Measure-22-Camouflage#1]
![shot-18 04 28_16 27 36-0928](https://user-images.githubusercontent.com/38806199/39393602-174c9002-4b02-11e8-8ace-db44ae7e5b14.jpg)
![shot-18 04 28_16 27 48-0472](https://user-images.githubusercontent.com/38806199/39393604-19fe9548-4b02-11e8-8522-82553757cacf.jpg)

Hello, I'm the user who loves your MS-22 camos.

after 0.7.4,

the model of baltimore and new orleans were somewhat updated.

I guess because of that; your camo doesn't look perfectly fit. More specifically, the waterline.

as you see in my uploaded screenshot.

by the way, I have gratitude for your contribution. 

thank you

syju1984

**Comment by Avalon304** [comment]
Fixed! Please redownload the pack! Thanks for the report with pictures, was very helpful!

**Comment by syju1984** [comment]
I'm satisfied with the update! Thank you.
