### ISSUE TITLE
New glitch introduced in 7.5.0

### ISSUE THREAD

**Issue by syju1984** [Avalon304/Functioning-Measure-22-Camouflage#2]
![shot-18 05 31_21 44 50-0588](https://user-images.githubusercontent.com/38806199/40783106-6718a2d6-651c-11e8-9b4d-48ce435389ec.jpg)

Hello.

I'm glad that buffalo was already good shape 

But the baltimore has a glitch.

Please see the picture of it. 

Thank you.

**Comment by Avalon304** [comment]
Fixed. Please update. Thanks!

**Comment by syju1984** [comment]
Thank you. It is perfectly fixed. I will enjoy your camos!
