### ISSUE TITLE
light cruiser update

### ISSUE THREAD

**Issue by syju1984** [Avalon304/Functioning-Measure-22-Camouflage#3]
I heard you need a ship to make the camo.

So I took the screenshots of the permoflages.

Worcester
![shot-18 07 01_03 55 19-0509](https://user-images.githubusercontent.com/38806199/42128292-fa5ff0b6-7ce2-11e8-9f34-3ae57b2fbb84.jpg)
![shot-18 07 01_03 52 28-0216](https://user-images.githubusercontent.com/38806199/42128294-074cde56-7ce3-11e8-8749-c4d08bde2526.jpg)
![shot-18 07 01_03 52 36-0958](https://user-images.githubusercontent.com/38806199/42128295-0dd375d2-7ce3-11e8-907f-e2fbf7ee1ff7.jpg)
![shot-18 07 01_03 52 50-0586](https://user-images.githubusercontent.com/38806199/42128296-12aa53e6-7ce3-11e8-9c5f-8aa905fb0b85.jpg)

Hellena
![shot-18 07 01_03 53 16-0910](https://user-images.githubusercontent.com/38806199/42128300-1b277224-7ce3-11e8-94e2-9c9c16ede9b1.jpg)
![shot-18 07 01_03 54 09-0386](https://user-images.githubusercontent.com/38806199/42128302-2007e1c0-7ce3-11e8-9a53-804c7f64ae2f.jpg)

Dallas
![shot-18 07 01_03 54 30-0954](https://user-images.githubusercontent.com/38806199/42128303-286b5130-7ce3-11e8-896b-5cd31736c138.jpg)
![shot-18 07 01_03 54 38-0828](https://user-images.githubusercontent.com/38806199/42128305-2b9ba0bc-7ce3-11e8-935a-6265988f9482.jpg)

That's it.

I don't have the seattle. If I get it, then I will upload. Of course only if you got help from the screenshots.

I make a closeup shot of the worcester because I guess there is a boundary between two diff. a color that would help to make ms-22 painting.

I hope these screenshots help you to convey.

Sincerely yours.

**Comment by Avalon304** [comment]
Thank you! These should be helpful in knowing where I need to make changes.

**Comment by syju1984** [comment]
![shot-18 07 02_22 46 19-0987](https://user-images.githubusercontent.com/38806199/42167769-fe890aa2-7e49-11e8-9b05-8276c02cf174.jpg)
![shot-18 07 02_22 46 55-0782](https://user-images.githubusercontent.com/38806199/42167773-01dba228-7e4a-11e8-8d8b-a873007a66cc.jpg)
![shot-18 07 02_22 47 48-0692](https://user-images.githubusercontent.com/38806199/42167779-040cf45c-7e4a-11e8-9945-2cbbdc00c771.jpg)

Seattle

I could find some borderline for ms-22 in the portside of the ship.

**Comment by Avalon304** [comment]
Thanks for your pictures they were helpful! The pack now has support for the final 4 US light cruisers (Dallas, Helena, Seattle and Worcester). Please update!

**Comment by syju1984** [comment]
![shot-18 07 07_16 55 58-0412](https://user-images.githubusercontent.com/38806199/42408373-ab07125a-8206-11e8-8cac-62e8e93ae33f.jpg)

![shot-18 07 07_16 53 13-0310](https://user-images.githubusercontent.com/38806199/42408364-7e2e77d2-8206-11e8-9c42-bf94b33b3a81.jpg)
![shot-18 07 07_16 53 55-0894](https://user-images.githubusercontent.com/38806199/42408366-7f5898ae-8206-11e8-827f-9507cfb5d93c.jpg)

thank you! Again lovely ships!
