### ISSUE TITLE
Thanks for the update. But the helena

### ISSUE THREAD

**Issue by syju1984** [Avalon304/Functioning-Measure-22-Camouflage#4]
![shot-18 07 07_20 52 46-0251](https://user-images.githubusercontent.com/38806199/42410658-242501f8-8228-11e8-9692-0abcc0e3171d.jpg)
![shot-18 07 07_20 53 03-0248](https://user-images.githubusercontent.com/38806199/42410662-33febcfe-8228-11e8-879e-0af64c0c6d61.jpg)
![shot-18 07 07_20 53 05-0662](https://user-images.githubusercontent.com/38806199/42410663-35b8af78-8228-11e8-8c8d-198f679be305.jpg)

I have been happy since your update.

Thank you.

**Comment by Avalon304** [comment]
Missing file. Sorry about that. Fixed now. Please reupdate.
